drop table user  if exists;
create table user (
  id bigint generated by default as identity ,
  username varchar(40),
  name varchar(20),
  age int(3),
  balance decimal (10,2),
  primary key (id)
);
drop table elevator_car  if exists;
create table elevator_car (
    id bigint generated by default as identity ,
    direction varchar(10),
    floor int,
    forward_floor int,
    highest_floor int,
    lowest_floor int,
    status varchar(10),
    region_id varchar(100)
);

